import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "var(--surface-tint)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        error: "var(--error)",
        background: "var(--background)",
        surface: "var(--surface)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "primary-container": "var(--primary-container)",
        "on-surface": "var(--on-surface)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "on-background": "var(--on-background)",
        "secondary-container": "var(--secondary-container)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        primary: "var(--primary)",
        "surface-variant": "var(--surface-variant)",
        outline: "var(--outline)",
        "on-tertiary": "var(--on-tertiary)",
        "on-secondary": "var(--on-secondary)",
        "outline-variant": "var(--outline-variant)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "surface-container-low": "var(--surface-container-low)",
        "on-primary-container": "var(--on-primary-container)",
        "surface-container-high": "var(--surface-container-high)",
        "on-error-container": "var(--on-error-container)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "surface-bright": "var(--surface-bright)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        secondary: "var(--secondary)",
        "inverse-primary": "var(--inverse-primary)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "surface-dim": "var(--surface-dim)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        tertiary: "var(--tertiary)",
        "error-container": "var(--error-container)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "surface-container": "var(--surface-container)",
        "primary-fixed": "var(--primary-fixed)",
        "on-secondary-container": "var(--on-secondary-container)",
        "tertiary-container": "var(--tertiary-container)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-primary": "var(--on-primary)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "inverse-surface": "var(--inverse-surface)",
        "on-error": "var(--on-error)",
        "secondary-fixed": "var(--secondary-fixed)",
      },
      fontFamily: {
        headline: ["var(--font-newsreader)", "serif"],
        body: ["var(--font-plus-jakarta)", "sans-serif"],
        label: ["var(--font-plus-jakarta)", "sans-serif"],
      },
      boxShadow: {
        warm: "0 10px 30px -15px rgba(31, 27, 15, 0.15)",
      },
      transitionTimingFunction: {
        smooth: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
